module.exports.i19 =
  'tor.checkdir' : "Checking config dir"
  'tor.readconf' : "Reading irac configuration"
  'init.otr' : "Generating OTR-Key (this may take a while)"
  'init.otr.done' : "OTR-Key was successfully generated"
  'tor.port' : "Checking if Tor is running"
  'tor.updaterc' : "Updating torrc"
  'tor.start' : "Starting Tor"
  'tor.ready' : "Tor is ready"
  'init.listen' : "IRAC service is listening"
  'init.callmyself' : "Trying to connect to myself"
  'init.callmyself.success' : "Ready"
